### ISSUE TITLE
Some questions about TORUS analysis

### ISSUE THREAD

**Issue by HelloWorldLTY** [kevinlkx/analysis_pipelines#1]
Hi, sorry to disturb you. I wonder if we can run TORUS analysis without the previous steps or not. Moreover, I wonder where can I find the data shown in this tutorial: 
https://kevinlkx.github.io/analysis_pipelines/mapgen_torus_enrichment_heart_atlas.html
Thanks a lot.

**Comment by kevinlkx** [comment]
Thanks for your interest. Sorry for the confusion. The analysis pipelines in this repo were written mainly for students in Xin He lab at U Chicago, so the data and scripts may not be accessible outside at this point. 

For the TORUS analysis, you only need GWAS or eQTL summary statistics, as well as SNP annotation files. See examples here: https://github.com/xqwen/torus/tree/master/examples. For more general use of TORUS, you may refer to the original tutorials of TORUS: https://github.com/xqwen/torus. 

You can find some example data of the heart atlas paper in our mapgen page https://kevinlkx.github.io/mapgen/index.html. (the software is still under development, and we will release more data later)

**Comment by HelloWorldLTY** [comment]
Thanks a lot.
