### ISSUE TITLE
Some questions about unlist/grange error

### ISSUE THREAD

**Issue by HelloWorldLTY** [kevinlkx/analysis_pipelines#2]
Hi, when I run codes here:
https://kevinlkx.github.io/analysis_pipelines/mapgen_torus_enrichment_heart_atlas.html
I received this error:
![image](https://user-images.githubusercontent.com/43333475/196288593-57ca0901-5997-40fe-adc6-12f5931b9bd7.png)

Could you please help me solve this problem? Thanks a lot.

**Comment by kevinlkx** [comment]
This works fine on my side. You can try using a for loop. 

This line of code is to liftOver the annotations from hg38 to hg19, in order to match with GWAS data which is in hg19. You don't need those if your annotations already match with the GWAS data.
